# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ArrangeShipmentReq(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'delivery_company': 'str',
        'delivery_no': 'str'
    }

    attribute_map = {
        'delivery_company': 'delivery_company',
        'delivery_no': 'delivery_no'
    }

    def __init__(self, delivery_company=None, delivery_no=None):  # noqa: E501
        """ArrangeShipmentReq - a model defined in Swagger"""  # noqa: E501
        self._delivery_company = None
        self._delivery_no = None
        self.discriminator = None
        self.delivery_company = delivery_company
        self.delivery_no = delivery_no

    @property
    def delivery_company(self):
        """Gets the delivery_company of this ArrangeShipmentReq.  # noqa: E501

         物流公司  # noqa: E501

        :return: The delivery_company of this ArrangeShipmentReq.  # noqa: E501
        :rtype: str
        """
        return self._delivery_company

    @delivery_company.setter
    def delivery_company(self, delivery_company):
        """Sets the delivery_company of this ArrangeShipmentReq.

         物流公司  # noqa: E501

        :param delivery_company: The delivery_company of this ArrangeShipmentReq.  # noqa: E501
        :type: str
        """
        if delivery_company is None:
            raise ValueError("Invalid value for `delivery_company`, must not be `None`")  # noqa: E501

        self._delivery_company = delivery_company

    @property
    def delivery_no(self):
        """Gets the delivery_no of this ArrangeShipmentReq.  # noqa: E501

         物流单号  # noqa: E501

        :return: The delivery_no of this ArrangeShipmentReq.  # noqa: E501
        :rtype: str
        """
        return self._delivery_no

    @delivery_no.setter
    def delivery_no(self, delivery_no):
        """Sets the delivery_no of this ArrangeShipmentReq.

         物流单号  # noqa: E501

        :param delivery_no: The delivery_no of this ArrangeShipmentReq.  # noqa: E501
        :type: str
        """
        if delivery_no is None:
            raise ValueError("Invalid value for `delivery_no`, must not be `None`")  # noqa: E501

        self._delivery_no = delivery_no

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ArrangeShipmentReq, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ArrangeShipmentReq):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
