# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ChangeOrderTotalReq(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'price': 'str',
        'postage': 'str'
    }

    attribute_map = {
        'price': 'price',
        'postage': 'Postage'
    }

    def __init__(self, price=None, postage=None):  # noqa: E501
        """ChangeOrderTotalReq - a model defined in Swagger"""  # noqa: E501
        self._price = None
        self._postage = None
        self.discriminator = None
        if price is not None:
            self.price = price
        self.postage = postage

    @property
    def price(self):
        """Gets the price of this ChangeOrderTotalReq.  # noqa: E501

         订单一口价格  # noqa: E501

        :return: The price of this ChangeOrderTotalReq.  # noqa: E501
        :rtype: str
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this ChangeOrderTotalReq.

         订单一口价格  # noqa: E501

        :param price: The price of this ChangeOrderTotalReq.  # noqa: E501
        :type: str
        """

        self._price = price

    @property
    def postage(self):
        """Gets the postage of this ChangeOrderTotalReq.  # noqa: E501

         邮费  # noqa: E501

        :return: The postage of this ChangeOrderTotalReq.  # noqa: E501
        :rtype: str
        """
        return self._postage

    @postage.setter
    def postage(self, postage):
        """Sets the postage of this ChangeOrderTotalReq.

         邮费  # noqa: E501

        :param postage: The postage of this ChangeOrderTotalReq.  # noqa: E501
        :type: str
        """
        if postage is None:
            raise ValueError("Invalid value for `postage`, must not be `None`")  # noqa: E501

        self._postage = postage

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChangeOrderTotalReq, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChangeOrderTotalReq):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
