# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateUserReq(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'username': 'str',
        'name': 'str',
        'email': 'str',
        'password': 'str',
        'role_ids': 'list[str]'
    }

    attribute_map = {
        'username': 'username',
        'name': 'name',
        'email': 'email',
        'password': 'password',
        'role_ids': 'role_ids'
    }

    def __init__(self, username=None, name=None, email=None, password=None, role_ids=None):  # noqa: E501
        """CreateUserReq - a model defined in Swagger"""  # noqa: E501
        self._username = None
        self._name = None
        self._email = None
        self._password = None
        self._role_ids = None
        self.discriminator = None
        self.username = username
        self.name = name
        self.email = email
        self.password = password
        self.role_ids = role_ids

    @property
    def username(self):
        """Gets the username of this CreateUserReq.  # noqa: E501

         用户名,规则:5-15位字母或数字  # noqa: E501

        :return: The username of this CreateUserReq.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this CreateUserReq.

         用户名,规则:5-15位字母或数字  # noqa: E501

        :param username: The username of this CreateUserReq.  # noqa: E501
        :type: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def name(self):
        """Gets the name of this CreateUserReq.  # noqa: E501

         用户昵称  # noqa: E501

        :return: The name of this CreateUserReq.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateUserReq.

         用户昵称  # noqa: E501

        :param name: The name of this CreateUserReq.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def email(self):
        """Gets the email of this CreateUserReq.  # noqa: E501

         用户邮箱  # noqa: E501

        :return: The email of this CreateUserReq.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this CreateUserReq.

         用户邮箱  # noqa: E501

        :param email: The email of this CreateUserReq.  # noqa: E501
        :type: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def password(self):
        """Gets the password of this CreateUserReq.  # noqa: E501

         用户密码, 规则:8-25位字符，必须包含字母、数字及特殊字符  # noqa: E501

        :return: The password of this CreateUserReq.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this CreateUserReq.

         用户密码, 规则:8-25位字符，必须包含字母、数字及特殊字符  # noqa: E501

        :param password: The password of this CreateUserReq.  # noqa: E501
        :type: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def role_ids(self):
        """Gets the role_ids of this CreateUserReq.  # noqa: E501

         绑定角色ID集合  # noqa: E501

        :return: The role_ids of this CreateUserReq.  # noqa: E501
        :rtype: list[str]
        """
        return self._role_ids

    @role_ids.setter
    def role_ids(self, role_ids):
        """Sets the role_ids of this CreateUserReq.

         绑定角色ID集合  # noqa: E501

        :param role_ids: The role_ids of this CreateUserReq.  # noqa: E501
        :type: list[str]
        """
        if role_ids is None:
            raise ValueError("Invalid value for `role_ids`, must not be `None`")  # noqa: E501

        self._role_ids = role_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateUserReq, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateUserReq):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
