# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InitSystemPermissionReq(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'secret': 'str',
        'permissions': 'str'
    }

    attribute_map = {
        'secret': 'secret',
        'permissions': 'permissions'
    }

    def __init__(self, secret=None, permissions=None):  # noqa: E501
        """InitSystemPermissionReq - a model defined in Swagger"""  # noqa: E501
        self._secret = None
        self._permissions = None
        self.discriminator = None
        self.secret = secret
        self.permissions = permissions

    @property
    def secret(self):
        """Gets the secret of this InitSystemPermissionReq.  # noqa: E501

         秘钥  # noqa: E501

        :return: The secret of this InitSystemPermissionReq.  # noqa: E501
        :rtype: str
        """
        return self._secret

    @secret.setter
    def secret(self, secret):
        """Sets the secret of this InitSystemPermissionReq.

         秘钥  # noqa: E501

        :param secret: The secret of this InitSystemPermissionReq.  # noqa: E501
        :type: str
        """
        if secret is None:
            raise ValueError("Invalid value for `secret`, must not be `None`")  # noqa: E501

        self._secret = secret

    @property
    def permissions(self):
        """Gets the permissions of this InitSystemPermissionReq.  # noqa: E501

         所有权限  # noqa: E501

        :return: The permissions of this InitSystemPermissionReq.  # noqa: E501
        :rtype: str
        """
        return self._permissions

    @permissions.setter
    def permissions(self, permissions):
        """Sets the permissions of this InitSystemPermissionReq.

         所有权限  # noqa: E501

        :param permissions: The permissions of this InitSystemPermissionReq.  # noqa: E501
        :type: str
        """
        if permissions is None:
            raise ValueError("Invalid value for `permissions`, must not be `None`")  # noqa: E501

        self._permissions = permissions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InitSystemPermissionReq, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InitSystemPermissionReq):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
