# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ListProductChild(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sku': 'str',
        'variation': 'str',
        'price': 'str',
        'stock': 'int',
        'sold': 'int',
        'sku_ver': 'int'
    }

    attribute_map = {
        'sku': 'sku',
        'variation': 'variation',
        'price': 'price',
        'stock': 'stock',
        'sold': 'sold',
        'sku_ver': 'skuVer'
    }

    def __init__(self, sku=None, variation=None, price=None, stock=None, sold=None, sku_ver=None):  # noqa: E501
        """ListProductChild - a model defined in Swagger"""  # noqa: E501
        self._sku = None
        self._variation = None
        self._price = None
        self._stock = None
        self._sold = None
        self._sku_ver = None
        self.discriminator = None
        self.sku = sku
        self.variation = variation
        self.price = price
        self.stock = stock
        self.sold = sold
        self.sku_ver = sku_ver

    @property
    def sku(self):
        """Gets the sku of this ListProductChild.  # noqa: E501

         商品sku  # noqa: E501

        :return: The sku of this ListProductChild.  # noqa: E501
        :rtype: str
        """
        return self._sku

    @sku.setter
    def sku(self, sku):
        """Sets the sku of this ListProductChild.

         商品sku  # noqa: E501

        :param sku: The sku of this ListProductChild.  # noqa: E501
        :type: str
        """
        if sku is None:
            raise ValueError("Invalid value for `sku`, must not be `None`")  # noqa: E501

        self._sku = sku

    @property
    def variation(self):
        """Gets the variation of this ListProductChild.  # noqa: E501

         商品规格信息  # noqa: E501

        :return: The variation of this ListProductChild.  # noqa: E501
        :rtype: str
        """
        return self._variation

    @variation.setter
    def variation(self, variation):
        """Sets the variation of this ListProductChild.

         商品规格信息  # noqa: E501

        :param variation: The variation of this ListProductChild.  # noqa: E501
        :type: str
        """
        if variation is None:
            raise ValueError("Invalid value for `variation`, must not be `None`")  # noqa: E501

        self._variation = variation

    @property
    def price(self):
        """Gets the price of this ListProductChild.  # noqa: E501

         价格  # noqa: E501

        :return: The price of this ListProductChild.  # noqa: E501
        :rtype: str
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this ListProductChild.

         价格  # noqa: E501

        :param price: The price of this ListProductChild.  # noqa: E501
        :type: str
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price

    @property
    def stock(self):
        """Gets the stock of this ListProductChild.  # noqa: E501

         库存  # noqa: E501

        :return: The stock of this ListProductChild.  # noqa: E501
        :rtype: int
        """
        return self._stock

    @stock.setter
    def stock(self, stock):
        """Sets the stock of this ListProductChild.

         库存  # noqa: E501

        :param stock: The stock of this ListProductChild.  # noqa: E501
        :type: int
        """
        if stock is None:
            raise ValueError("Invalid value for `stock`, must not be `None`")  # noqa: E501

        self._stock = stock

    @property
    def sold(self):
        """Gets the sold of this ListProductChild.  # noqa: E501

         销量  # noqa: E501

        :return: The sold of this ListProductChild.  # noqa: E501
        :rtype: int
        """
        return self._sold

    @sold.setter
    def sold(self, sold):
        """Sets the sold of this ListProductChild.

         销量  # noqa: E501

        :param sold: The sold of this ListProductChild.  # noqa: E501
        :type: int
        """
        if sold is None:
            raise ValueError("Invalid value for `sold`, must not be `None`")  # noqa: E501

        self._sold = sold

    @property
    def sku_ver(self):
        """Gets the sku_ver of this ListProductChild.  # noqa: E501

         skuVer  # noqa: E501

        :return: The sku_ver of this ListProductChild.  # noqa: E501
        :rtype: int
        """
        return self._sku_ver

    @sku_ver.setter
    def sku_ver(self, sku_ver):
        """Sets the sku_ver of this ListProductChild.

         skuVer  # noqa: E501

        :param sku_ver: The sku_ver of this ListProductChild.  # noqa: E501
        :type: int
        """
        if sku_ver is None:
            raise ValueError("Invalid value for `sku_ver`, must not be `None`")  # noqa: E501

        self._sku_ver = sku_ver

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ListProductChild, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListProductChild):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
