# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RoleDetail(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'menu': 'str',
        'permission': 'list[Detail]',
        'children': 'list[RoleDetail]'
    }

    attribute_map = {
        'menu': 'menu',
        'permission': 'permission',
        'children': 'children'
    }

    def __init__(self, menu=None, permission=None, children=None):  # noqa: E501
        """RoleDetail - a model defined in Swagger"""  # noqa: E501
        self._menu = None
        self._permission = None
        self._children = None
        self.discriminator = None
        self.menu = menu
        self.permission = permission
        self.children = children

    @property
    def menu(self):
        """Gets the menu of this RoleDetail.  # noqa: E501

         菜单名称  # noqa: E501

        :return: The menu of this RoleDetail.  # noqa: E501
        :rtype: str
        """
        return self._menu

    @menu.setter
    def menu(self, menu):
        """Sets the menu of this RoleDetail.

         菜单名称  # noqa: E501

        :param menu: The menu of this RoleDetail.  # noqa: E501
        :type: str
        """
        if menu is None:
            raise ValueError("Invalid value for `menu`, must not be `None`")  # noqa: E501

        self._menu = menu

    @property
    def permission(self):
        """Gets the permission of this RoleDetail.  # noqa: E501

         权限或者分组集合  # noqa: E501

        :return: The permission of this RoleDetail.  # noqa: E501
        :rtype: list[Detail]
        """
        return self._permission

    @permission.setter
    def permission(self, permission):
        """Sets the permission of this RoleDetail.

         权限或者分组集合  # noqa: E501

        :param permission: The permission of this RoleDetail.  # noqa: E501
        :type: list[Detail]
        """
        if permission is None:
            raise ValueError("Invalid value for `permission`, must not be `None`")  # noqa: E501

        self._permission = permission

    @property
    def children(self):
        """Gets the children of this RoleDetail.  # noqa: E501

         子级  # noqa: E501

        :return: The children of this RoleDetail.  # noqa: E501
        :rtype: list[RoleDetail]
        """
        return self._children

    @children.setter
    def children(self, children):
        """Sets the children of this RoleDetail.

         子级  # noqa: E501

        :param children: The children of this RoleDetail.  # noqa: E501
        :type: list[RoleDetail]
        """
        if children is None:
            raise ValueError("Invalid value for `children`, must not be `None`")  # noqa: E501

        self._children = children

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RoleDetail, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RoleDetail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
