# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_admin
from swagger_admin.AdminApi.role_api import RoleApi  # noqa: E501
from swagger_admin.rest import ApiException


class TestRoleApi(unittest.TestCase):
    """RoleApi unit test stubs"""

    def setUp(self):
        self.api = RoleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_role(self):
        """Test case for create_role

        创建角色  # noqa: E501
        """
        pass

    def test_delete_role(self):
        """Test case for delete_role

        删除角色  # noqa: E501
        """
        pass

    def test_exist_role_by_name(self):
        """Test case for exist_role_by_name

        角色是否存在  # noqa: E501
        """
        pass

    def test_get_all_permission(self):
        """Test case for get_all_permission

        获取所有权限包含分类  # noqa: E501
        """
        pass

    def test_get_role_detail(self):
        """Test case for get_role_detail

        角色详情  # noqa: E501
        """
        pass

    def test_list_role(self):
        """Test case for list_role

        角色列表  # noqa: E501
        """
        pass

    def test_permission_by_uuid(self):
        """Test case for permission_by_uuid

        获取指定用户的所有权限包含分类  # noqa: E501
        """
        pass

    def test_update_role(self):
        """Test case for update_role

        修改角色  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
