# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_admin
from swagger_admin.AdminModel.product_info import ProductInfo  # noqa: E501
from swagger_admin.rest import ApiException


class TestProductInfo(unittest.TestCase):
    """ProductInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductInfo(self):
        """Test ProductInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_admin.models.product_info.ProductInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
