# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_admin
from swagger_admin.AdminModel.create_freight_template_req import CreateFreightTemplateReq  # noqa: E501
from swagger_admin.rest import ApiException


class TestCreateFreightTemplateReq(unittest.TestCase):
    """CreateFreightTemplateReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateFreightTemplateReq(self):
        """Test CreateFreightTemplateReq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_admin.models.create_freight_template_req.CreateFreightTemplateReq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
