# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_admin
from swagger_admin.AdminModel.empty_role import EmptyRole  # noqa: E501
from swagger_admin.rest import ApiException


class TestEmptyRole(unittest.TestCase):
    """EmptyRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmptyRole(self):
        """Test EmptyRole"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_admin.models.empty_role.EmptyRole()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
