# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_admin
from swagger_admin.AdminApi.group_api import GroupApi  # noqa: E501
from swagger_admin.rest import ApiException


class TestGroupApi(unittest.TestCase):
    """GroupApi unit test stubs"""

    def setUp(self):
        self.api = GroupApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_group(self):
        """Test case for create_group

        创建分组/子分组  # noqa: E501
        """
        pass

    def test_delete_group(self):
        """Test case for delete_group

        删除分组  # noqa: E501
        """
        pass

    def test_list_group(self):
        """Test case for list_group

        分组列表  # noqa: E501
        """
        pass

    def test_update_group(self):
        """Test case for update_group

        更新分组  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
