# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_admin
from swagger_admin.AdminModel.get_product_req import GetProductReq  # noqa: E501
from swagger_admin.rest import ApiException


class TestGetProductReq(unittest.TestCase):
    """GetProductReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetProductReq(self):
        """Test GetProductReq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_admin.models.get_product_req.GetProductReq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
