# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_admin
from swagger_admin.AdminModel.change_publish_status_products_req import ChangePublishStatusProductsReq  # noqa: E501
from swagger_admin.rest import ApiException


class TestChangePublishStatusProductsReq(unittest.TestCase):
    """ChangePublishStatusProductsReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChangePublishStatusProductsReq(self):
        """Test ChangePublishStatusProductsReq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_admin.models.change_publish_status_products_req.ChangePublishStatusProductsReq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
