# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_admin
from swagger_admin.AdminModel.list_users_resp import ListUsersResp  # noqa: E501
from swagger_admin.rest import ApiException


class TestListUsersResp(unittest.TestCase):
    """ListUsersResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListUsersResp(self):
        """Test ListUsersResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_admin.models.list_users_resp.ListUsersResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
