# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_admin
from swagger_admin.AdminApi.public_api import PublicApi  # noqa: E501
from swagger_admin.rest import ApiException


class TestPublicApi(unittest.TestCase):
    """PublicApi unit test stubs"""

    def setUp(self):
        self.api = PublicApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_clear_system_permission(self):
        """Test case for clear_system_permission

        清除系统所有权限  # noqa: E501
        """
        pass

    def test_init_system_permission(self):
        """Test case for init_system_permission

        初始化系统所有权限  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
