# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_admin
from swagger_admin.AdminApi.order_api import OrderApi  # noqa: E501
from swagger_admin.rest import ApiException


class TestOrderApi(unittest.TestCase):
    """OrderApi unit test stubs"""

    def setUp(self):
        self.api = OrderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_arrange_shipment(self):
        """Test case for arrange_shipment

        待发货订单,安排发货完善物流信息  # noqa: E501
        """
        pass

    def test_change_order_total(self):
        """Test case for change_order_total

        未支付订单,修改一口价/邮费  # noqa: E501
        """
        pass

    def test_export_order(self):
        """Test case for export_order

        订单导出  # noqa: E501
        """
        pass

    def test_get_order(self):
        """Test case for get_order

        订单详情  # noqa: E501
        """
        pass

    def test_list_order(self):
        """Test case for list_order

        订单列表  # noqa: E501
        """
        pass

    def test_update_order_note(self):
        """Test case for update_order_note

        修改订单note  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
