# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_admin
from swagger_admin.AdminModel.update_stock_product_req import UpdateStockProductReq  # noqa: E501
from swagger_admin.rest import ApiException


class TestUpdateStockProductReq(unittest.TestCase):
    """UpdateStockProductReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateStockProductReq(self):
        """Test UpdateStockProductReq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_admin.models.update_stock_product_req.UpdateStockProductReq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
