# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_admin
from swagger_admin.AdminApi.user_api import UserApi  # noqa: E501
from swagger_admin.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_users(self):
        """Test case for create_users

        创建用户  # noqa: E501
        """
        pass

    def test_delete_user(self):
        """Test case for delete_user

        删除用户  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        用户详情  # noqa: E501
        """
        pass

    def test_list_users(self):
        """Test case for list_users

        用户列表  # noqa: E501
        """
        pass

    def test_reset_password_user(self):
        """Test case for reset_password_user

        重置用户密码  # noqa: E501
        """
        pass

    def test_update_user(self):
        """Test case for update_user

        修改用户信息  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
