# coding: utf-8

"""

    认证服务后台api  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_service
from swagger_service.ServiceModel.session_refresh_req import SessionRefreshReq  # noqa: E501
from swagger_service.rest import ApiException


class TestSessionRefreshReq(unittest.TestCase):
    """SessionRefreshReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSessionRefreshReq(self):
        """Test SessionRefreshReq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_service.models.session_refresh_req.SessionRefreshReq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
