# coding: utf-8

"""

    认证服务后台api  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_service
from swagger_service.ServiceModel.update_profile_req import UpdateProfileReq  # noqa: E501
from swagger_service.rest import ApiException


class TestUpdateProfileReq(unittest.TestCase):
    """UpdateProfileReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateProfileReq(self):
        """Test UpdateProfileReq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_service.models.update_profile_req.UpdateProfileReq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
