# coding: utf-8

"""

    认证服务后台api  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_service
from swagger_service.ServiceModel.register_google_req import RegisterGoogleReq  # noqa: E501
from swagger_service.rest import ApiException


class TestRegisterGoogleReq(unittest.TestCase):
    """RegisterGoogleReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegisterGoogleReq(self):
        """Test RegisterGoogleReq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_service.models.register_google_req.RegisterGoogleReq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
