# coding: utf-8

"""

    认证服务后台api  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_service
from swagger_service.ServiceModel.verify_phone_code_resp import VerifyPhoneCodeResp  # noqa: E501
from swagger_service.rest import ApiException


class TestVerifyPhoneCodeResp(unittest.TestCase):
    """VerifyPhoneCodeResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVerifyPhoneCodeResp(self):
        """Test VerifyPhoneCodeResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_service.models.verify_phone_code_resp.VerifyPhoneCodeResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
