# coding: utf-8

"""

    认证服务后台api  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_service
from swagger_service.ServiceApi.register_api import RegisterApi  # noqa: E501
from swagger_service.rest import ApiException


class TestRegisterApi(unittest.TestCase):
    """RegisterApi unit test stubs"""

    def setUp(self):
        self.api = RegisterApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_register_google(self):
        """Test case for register_google

        google登录  # noqa: E501
        """
        pass

    def test_register_phone_number(self):
        """Test case for register_phone_number

        手机号注册step2-注册  # noqa: E501
        """
        pass

    def test_register_sms(self):
        """Test case for register_sms

        手机号注册step1-发送短信  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
