# coding: utf-8

"""

    认证服务后台api  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_service
from swagger_service.ServiceModel.login_resp import LoginResp  # noqa: E501
from swagger_service.rest import ApiException


class TestLoginResp(unittest.TestCase):
    """LoginResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoginResp(self):
        """Test LoginResp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_service.models.login_resp.LoginResp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
