# coding: utf-8

"""

    认证服务后台api  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_service
from swagger_service.ServiceApi.auth_api import AuthApi  # noqa: E501
from swagger_service.rest import ApiException


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self):
        self.api = AuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_init_password(self):
        """Test case for init_password

        注册初次设置密码  # noqa: E501
        """
        pass

    def test_unique_email(self):
        """Test case for unique_email

        验证邮箱唯一性  # noqa: E501
        """
        pass

    def test_unique_phone_number(self):
        """Test case for unique_phone_number

        验证手机号唯一性  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
