# coding: utf-8

"""

    认证服务后台api  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_service
from swagger_service.ServiceApi.password_api import PasswordApi  # noqa: E501
from swagger_service.rest import ApiException


class TestPasswordApi(unittest.TestCase):
    """PasswordApi unit test stubs"""

    def setUp(self):
        self.api = PasswordApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_email_forget_pwd(self):
        """Test case for email_forget_pwd

        忘记密码step1-发送邮件  # noqa: E501
        """
        pass

    def test_reset_password(self):
        """Test case for reset_password

        忘记密码step3-修改密码  # noqa: E501
        """
        pass

    def test_sms_forget_pwd(self):
        """Test case for sms_forget_pwd

        忘记密码step1-发送手机短信  # noqa: E501
        """
        pass

    def test_update_password(self):
        """Test case for update_password

        个人中心修改密码  # noqa: E501
        """
        pass

    def test_verify_email_code(self):
        """Test case for verify_email_code

        忘记密码step2-验证邮件验证码  # noqa: E501
        """
        pass

    def test_verify_phone_code(self):
        """Test case for verify_phone_code

        忘记密码step2-验证手机验证码  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
