# coding: utf-8

"""

    认证服务后台api  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_service
from swagger_service.ServiceApi.profile_api import ProfileApi  # noqa: E501
from swagger_service.rest import ApiException


class TestProfileApi(unittest.TestCase):
    """ProfileApi unit test stubs"""

    def setUp(self):
        self.api = ProfileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_update_phone_number_new_sms(self):
        """Test case for update_phone_number_new_sms

        个人中心修改手机号step3-新手机号发送短信  # noqa: E501
        """
        pass

    def test_update_phone_number_old_sms(self):
        """Test case for update_phone_number_old_sms

        个人中心修改手机号step1-旧手机号发送短信  # noqa: E501
        """
        pass

    def test_update_profile(self):
        """Test case for update_profile

        设置用户名/姓名  # noqa: E501
        """
        pass

    def test_verify_new_phone_number(self):
        """Test case for verify_new_phone_number

        个人中心修改手机号step4-验证新手机号  # noqa: E501
        """
        pass

    def test_verify_old_phone_number(self):
        """Test case for verify_old_phone_number

        个人中心修改手机号step2-验证旧手机号  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
