# coding: utf-8

"""

    认证服务后台api  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_service
from swagger_service.ServiceApi.session_api import SessionApi  # noqa: E501
from swagger_service.rest import ApiException


class TestSessionApi(unittest.TestCase):
    """SessionApi unit test stubs"""

    def setUp(self):
        self.api = SessionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_session_info(self):
        """Test case for get_session_info

        获取accesstoken用户信息  # noqa: E501
        """
        pass

    def test_login_sms(self):
        """Test case for login_sms

        手机号登录step1-发送短信  # noqa: E501
        """
        pass

    def test_logout(self):
        """Test case for logout

        登出  # noqa: E501
        """
        pass

    def test_password_login(self):
        """Test case for password_login

        手机号密码登录  # noqa: E501
        """
        pass

    def test_phone_login(self):
        """Test case for phone_login

        手机号登录step2-登录  # noqa: E501
        """
        pass

    def test_session_refresh(self):
        """Test case for session_refresh

        使用refresh获取新的token  # noqa: E501
        """
        pass

    def test_user_login(self):
        """Test case for user_login

        用户名密码登录  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
